import Link from "next/link";
import { notFound } from "next/navigation";
import { MenuManagement } from "@/components/menu/menu-management";
import { DuePayments } from "@/components/pos/due-payments";
import { InventoryPage } from "@/components/inventory/inventory-page";
import { AddInventoryItem } from "@/components/inventory/add-inventory-item";
import { TableManagement } from "@/components/pos/table-management";
const labels:Record<string,{title:string;description:string;columns:string[]}>={
 tables:{title:"Tables",description:"See table availability and open orders.",columns:["Table","Seats","Status","Current order","Total"]},
 menu:{title:"Menu",description:"Maintain categories and saleable menu items.",columns:["Name","Category","Price","Active","Actions"]}, customers:{title:"Customers",description:"Search customer profiles, dues and order history.",columns:["Name","Phone","Orders","Total spent","Due"]},
 "due-payments":{title:"Due Payments",description:"Review customer balances and outstanding payments.",columns:["Customer","Phone","Balance due","Last payment","Actions"]},
 inventory:{title:"Inventory",description:"Current stock, minimum levels and adjustment controls.",columns:["Item","SKU","Unit","Current stock","Status"]}, purchases:{title:"Purchases",description:"Record supplier purchases and stock receipts.",columns:["Date","Supplier","Items","Total","Status"]}, suppliers:{title:"Suppliers",description:"Manage supplier profiles and purchase history.",columns:["Supplier","Phone","Purchases","Balance","Status"]}, expenses:{title:"Expenses",description:"Record expenses; use reversal instead of deleting completed records.",columns:["Date","Category","Description","Amount","Payment method"]}, reports:{title:"Reports",description:"Filter operational reports by date and export the current view.",columns:["Report","Period","Gross sales","Tax","Net sales"]}, audit:{title:"Audit log",description:"Review changes, reasons and before/after values.",columns:["Time","User","Action","Entity","Reference"]}, settings:{title:"Settings",description:"Cafe profile, operating preferences and team access.",columns:["Setting","Value","Last updated","Actions"]}
};
export default async function Catchall({params}:{params:Promise<{slug:string[]}>}){const {slug}=await params;if(["audit","expenses","customers"].includes(slug[0]))notFound();if(slug[0]==="tables")return <TableManagement/>;if(slug[0]==="menu")return <MenuManagement/>;if(slug[0]==="due-payments")return <DuePayments/>;if(slug[0]==="inventory"&&slug[1]==="new")return <AddInventoryItem/>;if(slug[0]==="inventory"&&!slug[1])return <InventoryPage/>;const section=labels[slug[0]]||{title:slug.map(s=>s.replaceAll("-"," ")).join(" / "),description:"Manage this cafe workspace.",columns:["Name","Status","Updated","Actions"]};return <><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><h1 className="page-title">{section.title}</h1><p className="muted">{section.description}</p></div><button className="btn">Add new</button></div><div className="card" style={{marginTop:20,overflowX:"auto"}}><div className="form-row"><label className="field">Search<input placeholder="Search records"/></label><label className="field">Date range<input type="date"/></label><button className="btn secondary">Refresh</button><button className="btn secondary">Export</button></div><table className="table"><thead><tr>{section.columns.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody><tr>{section.columns.map((x,i)=><td key={x}>{i===0?"No records to display":i===1?<span className="tag">—</span>:"—"}</td>)}</tr></tbody></table><p className="empty">No matching records yet. Use the action above to add one.</p></div>{slug[0]==="inventory"&&slug[1]==="low-stock"&&<Link href="/purchases" className="btn">Create purchase</Link>}</>}
